name: MCBriscola
version: '${project.version}'
main: me.mailo.mcbriscola.MCBriscola
api-version: '1.20'
description: Classic Italian Card Game Briscola in Minecraft
authors:
  - Harly47 (The Implementation on Minecraft)
  - Fmarco98 (The Basic Logic)
commands:
  briscola:
    description: Main command of the plugin

